### ISSUE TITLE
Proposal: Establish an Organization for Maintaining Unofficial KernelSU

### ISSUE THREAD

**Issue by Nobooooody** [rifsxd/KernelSU-Next#11]
### Description:  
To enhance collaboration and reduce fragmentation within the community, I propose creating a dedicated organization to maintain Unofficial KernelSU.  

### Key Points:  
1. **Unified Repository:**  
   - Merge universally accepted components from different Unofficial KernelSU repositories into a single, centralized project.  

2. **Forks for Conflicting Parts:**  
   - Address areas of disagreement by implementing them in separate forks under the same organization.  

3. **Reduce Fragmentation:**  
   - This approach will minimize fragmentation across the community and provide a more cohesive development environment.  

4. **Streamlined Maintenance:**  
   - Consolidating efforts under one organization will significantly reduce the workload for maintaining multiple Unofficial KernelSU repositories.  

### Benefits:  
- Improved collaboration among developers.  
- Easier adoption of updates and improvements.  
- Better organization and clarity for contributors and users.  

Let me know your thoughts or suggestions!

**Comment by th1nhhdk** [comment]
Yes, a GitHub organization should be created, and rifsxd should make a fork of the KernelSU website (instead of using the original website)

**Comment by rifsxd** [comment]
Ask the other popular fork owners

**Comment by rifsxd** [comment]
Closing as of now.
