### ISSUE TITLE
Regarding the cloned branch susfs-4.9, is it necessary to patch KernelSU?

### ISSUE THREAD

**Issue by Fyj69** [rifsxd/KernelSU-Next#18]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Hello, I have cloned the repository branch susfs-4.9, do I need to follow the tutorial in the susfs4ksu official repository branch kernel-4.9?

Patch Instruction (For non-GKI only)

Clone the repo with a tag that has release version, as tag with release version is more stable
Run cp ./kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch $KERNEL_ROOT/KernelSU/

Run cp ./kernel_patches/50_add_susfs_in_kernel-<kernel_version>.patch $KERNEL_ROOT/

Run cp ./kernel_patches/fs/susfs.c $KERNEL_ROOT/fs/

Run cp ./kernel_patches/include/linux/susfs.h $KERNEL_ROOT/include/linux/

Run cd $KERNEL_ROOT/KernelSU and then patch -p1 < 10_enable_susfs_for_ksu.patch

Run cd $KERNEL_ROOT and then patch -p1 < 50_add_susfs_in_kernel.patch, if there are failed patches, you may try to patch them manually by yourself.

Make sure again to have CONFIG_KSU and CONFIG_KSU_SUSFS enabled before building the kernel, some other SUSFS feature may be disabled by default, you may enable/disable them via menuconfig, kernel defconfig, or change the default [y|n] option under each config KSU_SUSFS_ option in $KernelSU_repo/kernel/Kconfig if you build with a new defconfig every time.
If your kernel already has the KSU non-kprobe hook patches applied, then you have to DISABLE the CONFIG_KSU_SUSFS_SUS_SU option.
For some compilor error, please refer to the section [Known Compilor Issues] below.
For other building tips, please refer to the section [Other Building Tips] below.

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by rifsxd** [comment]
The branch is already patched hence the branch name is susfs-xxx so no need to patch, you only have to make sure you patch your kernel only
