### ISSUE TITLE
[question] How can i compile GKI with KSU-Next and SUSFS included?

### ISSUE THREAD

**Issue by ambatubash69** [rifsxd/KernelSU-Next#25]
### Describe your problem.

i want to compile gki android12-5.10 with ksu next and susfs included, could you check my build script?

https://github.com/ambatubash69/gki-builder/blob/feature/KSU-Next/build.sh

**Comment by rifsxd** [comment]
your "$GKI_VERSION" will output android12-5.10 while the susfs branch needs susfs-a2-5.10

**Comment by ambatubash69** [comment]
> your "$GKI_VERSION" will output android12-5.10 while the susfs branch needs susfs-a2-5.10

besides that?

**Comment by rifsxd** [comment]
> > your "$GKI_VERSION" will output android12-5.10 while the susfs branch needs susfs-a2-5.10
> 
> besides that?

Nothing I guess and btw redo the branch name next-susfs-*

**Comment by ambatubash69** [comment]
> > > your "$GKI_VERSION" will output android12-5.10 while the susfs branch needs susfs-a2-5.10
> > 
> > 
> > besides that?
> 
> Nothing I guess and btw redo the branch name next-susfs-*


okay thanks
