### ISSUE TITLE
Tracking SUSFS Patches

### ISSUE THREAD

**Issue by hopez13** [rifsxd/KernelSU-Next#29]
### Describe your problem.

Please include the corresponding commit link  from https://gitlab.com/simonpunk/susfs4ksu in commit message that corresponds to the SUSFS patches applied
So That We Can Apply Corresponding Kernel Patches From Same Commit 
As Susfs Is Being Updated Frequently 

To Make Sure Susfs  Kernel And KSU Patches align

Note that there is no 1.5.3 tag in that repository

**Comment by rifsxd** [comment]
Noted

**Comment by qwerzxcva** [comment]
> 著名的

Hi, how do I patch susfs on non-gki? If it's gki, can I swipe its boot and use the susfs module?
