### ISSUE TITLE
ksu_access_ok duplicate definition error

### ISSUE THREAD

**Issue by Fyj69** [rifsxd/KernelSU-Next#3]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Branch susfs-4.9 encountered a ksu_access_ok duplicate definition error during the compilation process, causing the kernel compilation to fail.

### To Reproduce

    CC      net/ipv4/ah4.o
    CC      net/ipv4/esp4.o
  ../drivers/kernelsu/kernel_compat.c:85:5: error: redefinition of 'ksu_access_ok'
  int ksu_access_ok(const void *addr, unsigned long size) {
      ^
  ../drivers/kernelsu/kernel_compat.c:75:5: note: previous definition is here
  int ksu_access_ok(const void *addr, unsigned long size) {
      ^
  1 error generated.
  make[4]: *** [../scripts/Makefile.build:339: drivers/kernelsu/kernel_compat.o] Error 1
  make[3]: *** [../scripts/Makefile.build:653: drivers/kernelsu] Error 2
  make[3]: *** Waiting for unfinished jobs....

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by rifsxd** [comment]
Fixed
