### ISSUE TITLE
Failed to grant root!

### ISSUE THREAD

**Issue by Fyj69** [rifsxd/KernelSU-Next#5]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Hello, boss, although the compilation was successful when using the branch susfs-4.9, KSU_SUSFS may not be friendly to my kernel, and I failed to obtain root permissions.

![69](https://github.com/user-attachments/assets/5267ab85-de0b-4a44-9d04-062350615182)

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by Fyj69** [comment]
[KernelSU_bugreport.tar.gz](https://github.com/user-attachments/files/18190547/KernelSU_bugreport.tar.gz)

**Comment by rifsxd** [comment]
Untill I've found the problem you can try susfs-4.9 branch of KernelSU Next

**Comment by rifsxd** [comment]
Try enabling all kprobes in your kernel.

**Comment by Fyj69** [comment]
> Try enabling all kprobes in your kernel.

My kernel version is 4.9.250, and I use the manually integrated KernelSU patch. According to the susfs4ksu author warehouse document: If your kernel already has the KSU non-kprobe hook patches applied, then you have to DISABLE the CONFIG_KSU_SUSFS_SUS_SU option. So no Determine if turning on all kprobe options solves the problem.

**Comment by Fyj69** [comment]
> > > Try enabling all kprobes in your kernel.
> > 
> > 
> > My kernel version is 4.9.250, and I use the manually integrated KernelSU patch. According to the susfs4ksu author warehouse document: If your kernel already has the KSU non-kprobe hook patches applied, then you have to DISABLE the CONFIG_KSU_SUSFS_SUS_SU option. So no Determine if turning on all kprobe options solves the problem.
> 
> Turn off sus_su then

See the KernelSU official website introduction: Entering safe mode accidentally?

If you use manual integration and do not disable CONFIG_KPROBES, then the user may trigger safe mode by pressing the volume down button after booting! Therefore if using manual integration you need to disable CONFIG_KPROBES!
So I don’t know if it will enter safe mode accidentally if it is turned on?

**Comment by Fyj69** [comment]
> I'm not asking you to enable kprobes if you have manual hooks, maybe your manual hooks is faulty that's why root not found

The strange thing is that I can obtain root privileges normally without entering the KSU_SUSFS patch.

![3](https://github.com/user-attachments/assets/c54b74bf-1677-4906-a159-ab081d832042)

**Comment by rifsxd** [comment]
> > I'm not asking you to enable kprobes if you have manual hooks, maybe your manual hooks is faulty that's why root not found
> 
> The strange thing is that I can obtain root privileges normally without applying the KSU_SUSFS patch.
> 
> ![3](https://private-user-images.githubusercontent.com/18164452/397783461-c54b74bf-1677-4906-a159-ab081d832042.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MDg2NDksIm5iZiI6MTczNDcwODM0OSwicGF0aCI6Ii8xODE2NDQ1Mi8zOTc3ODM0NjEtYzU0Yjc0YmYtMTY3Ny00OTA2LWExNTktYWIwODFkODMyMDQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDE1MjU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNjU2MjA5NjA3NjI2MGZmNDA1N2NjODY3NGRmZTJmNmI2YzA2YjQyMGJkMzViMWYwM2FmNWQ0MjMxNmJlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K5N5_7TvDfSV0-iksub83D9chwQ20OFvO1kSDBoE0Vg)

Then you may have patched wrong, instead use ksu-next's own susfs branch

**Comment by Fyj69** [comment]
> > > I'm not asking you to enable kprobes if you have manual hooks, maybe your manual hooks is faulty that's why root not found
> > 
> > 
> > The strange thing is that I can obtain root privileges normally without applying the KSU_SUSFS patch.
> > ![3](https://private-user-images.githubusercontent.com/18164452/397783461-c54b74bf-1677-4906-a159-ab081d832042.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MDg2NDksIm5iZiI6MTczNDcwODM0OSwicGF0aCI6Ii8xODE2NDQ1Mi8zOTc3ODM0NjEtYzU0Yjc0YmYtMTY3Ny00OTA2LWExNTktYWIwODFkODMyMDQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDE1MjU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNjU2MjA5NjA3NjI2MGZmNDA1N2NjODY3NGRmZTJmNmI2YzA2YjQyMGJkMzViMWYwM2FmNWQ0MjMxNmJlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K5N5_7TvDfSV0-iksub83D9chwQ20OFvO1kSDBoE0Vg)
> 
> Then you may have patched wrong, instead use ksu-next's own susfs branch

My kernel version is 4.9, and the selected branch is susfs-4.9. There should be no wrong patches.

![9](https://github.com/user-attachments/assets/bf06bc38-3a77-43ed-a00e-a109e381ff58)

**Comment by rifsxd** [comment]
> > > > I'm not asking you to enable kprobes if you have manual hooks, maybe your manual hooks is faulty that's why root not found
> > > 
> > > 
> > > The strange thing is that I can obtain root privileges normally without applying the KSU_SUSFS patch.
> > > ![3](https://private-user-images.githubusercontent.com/18164452/397783461-c54b74bf-1677-4906-a159-ab081d832042.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MDg2NDksIm5iZiI6MTczNDcwODM0OSwicGF0aCI6Ii8xODE2NDQ1Mi8zOTc3ODM0NjEtYzU0Yjc0YmYtMTY3Ny00OTA2LWExNTktYWIwODFkODMyMDQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDE1MjU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNjU2MjA5NjA3NjI2MGZmNDA1N2NjODY3NGRmZTJmNmI2YzA2YjQyMGJkMzViMWYwM2FmNWQ0MjMxNmJlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K5N5_7TvDfSV0-iksub83D9chwQ20OFvO1kSDBoE0Vg)
> > 
> > 
> > Then you may have patched wrong, instead use ksu-next's own susfs branch
> 
> My kernel version is 4.9, and the selected branch is susfs-4.9. There should be no wrong patches.
> 
> ![9](https://private-user-images.githubusercontent.com/18164452/397787877-bf06bc38-3a77-43ed-a00e-a109e381ff58.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MTQ1OTgsIm5iZiI6MTczNDcxNDI5OCwicGF0aCI6Ii8xODE2NDQ1Mi8zOTc3ODc4NzctYmYwNmJjMzgtM2E3Ny00M2VkLWEwMGUtYTEwOWUzODFmZjU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDE3MDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYzliYjQyN2NjYjEzZGVlYjZiZGNkYWJhNTE5Njc3MTYyYTQ5ZWI2MDI4NjIwMTE0ZTBlMjgyZDA5MzljZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.URxb3qyzrietyq2O335gyHEVRLbU13ZEaZzXjscENZQ)

Talk to susfs dev for possible code review of the susfs 4.9 patches, I think its not kernelsu-next related problem.

Closing issue.

**Comment by Fyj69** [comment]
Okay, by the way, to clone your repository, do you still need to follow the tutorial in the susfs4ksu official repository branch kernel-4.9?

Patch Instruction (For non-GKI only)

Clone the repo with a tag that has release version, as tag with release version is more stable
Run cp ./kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch $KERNEL_ROOT/KernelSU/

Run cp ./kernel_patches/50_add_susfs_in_kernel-<kernel_version>.patch $KERNEL_ROOT/

Run cp ./kernel_patches/fs/susfs.c $KERNEL_ROOT/fs/

Run cp ./kernel_patches/include/linux/susfs.h $KERNEL_ROOT/include/linux/

Run cd $KERNEL_ROOT/KernelSU and then patch -p1 < 10_enable_susfs_for_ksu.patch

Run cd $KERNEL_ROOT and then patch -p1 < 50_add_susfs_in_kernel.patch, if there are failed patches, you may try to patch them manually by yourself.

Make sure again to have CONFIG_KSU and CONFIG_KSU_SUSFS enabled before building the kernel, some other SUSFS feature may be disabled by default, you may enable/disable them via menuconfig, kernel defconfig, or change the default [y|n] option under each config KSU_SUSFS_ option in $KernelSU_repo/kernel/Kconfig if you build with a new defconfig every time.
If your kernel already has the KSU non-kprobe hook patches applied, then you have to DISABLE the CONFIG_KSU_SUSFS_SUS_SU option.
For some compilor error, please refer to the section [Known Compilor Issues] below.
For other building tips, please refer to the section [Other Building Tips] below.
