### ISSUE TITLE
Adaway not working/host files not working

### ISSUE THREAD

**Issue by ggeo-git** [rifsxd/KernelSU-Next#50]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I tried using these modules for Adaway: 
https://github.com/backslashxx/bindhosts/releases/tag/v1.8.4
https://github.com/symbuzzer/systemless-hosts-KernelSU-module/releases

and I was not successful, Adaway is not working, the ads are not being blocked

### To Reproduce

1: Install some of these two modules above
2: Lower the Adaway
3: click the red button to modify the host files
4: Go to a website that has ads and see if the ads have been blocked.
![Screenshot_20241226_232515_Chrome](https://github.com/user-attachments/assets/6d8a3aca-e27c-4a3b-8d2b-7c751ae77013)
![Screenshot_20241226_232446_KernelSU Next](https://github.com/user-attachments/assets/40d4f0ed-d5c1-43d3-9a6c-918f317f80ec)
[KernelSU_Next_bugreport_2024-12-26_23_26.tar.gz](https://github.com/user-attachments/files/18256778/KernelSU_Next_bugreport_2024-12-26_23_26.tar.gz)

### Expected behavior

.

### Screenshots

.

### Logs

.

### Device info

- Device: A03 (a035m)
- OS Version: Android 13 (A13)
- KernelSU Version: 12139
- Kernel Version: 4.14.199

### Additional context

.

**Comment by rifsxd** [comment]
Not related to KernelSU Next, chrome doesn't allow adblocking unless you disable chorme's secure dns and set private dns in android settings, and i would suggest using bindhosts module insetad of adaway or systemless hosts
