### ISSUE TITLE
Is it possible to build it with broken KProbe?

### ISSUE THREAD

**Issue by DADA30000** [rifsxd/KernelSU-Next#53]
### Describe your problem.

I have bootloop if I enable KProbe, but some guy managed to build my kernel with original KSU by manually patching it, can I do the same, or do I even need to do the same? Maybe I just need to disable KProbe and it will work?
If I try to building without KProbe enabled with SUSFS patches, I get same error as in #5, my kernel version is 4.19
EDIT: when using manual integration, I get error that ksu_hook.h is not found

**Comment by Tsewingto** [comment]
创建临时失败

**Comment by DADA30000** [comment]
nvm, the problem was with KSU in general, so this is another useless issue, sorry :P
