### ISSUE TITLE
创建临时目录失败

### ISSUE THREAD

**Issue by Tsewingto** [rifsxd/KernelSU-Next#54]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

导入内核时创建临时目录失败

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by rifsxd** [comment]
You haven't provided no logs not device Info or any info to work with

**Comment by rifsxd** [comment]
Closing issue as no required info was given
