### ISSUE TITLE
[Custom] Request to add detailed guide on compiling non-GKI kernels

### ISSUE THREAD

**Issue by postcumer** [rifsxd/KernelSU-Next#55]
### Describe your problem.

I found no detailed guide on compiling KernelSU-Next like the  legacy KernelSU has on it's website, I understand only you working on the project is very big responsibility on it's own, it's just a request I would like you to see through. :P

**Comment by rifsxd** [comment]
> ### Describe your problem.
> I found no detailed guide on compiling KernelSU-Next like the legacy KernelSU has on it's website, I understand only you working on the project is very big responsibility on it's own, it's just a request I would like you to see through. :P

Follows the same guide of Legacy
