### ISSUE TITLE
Module opening problem

### ISSUE THREAD

**Issue by Fyj69** [rifsxd/KernelSU-Next#57]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When using the latest version, the module cannot be opened. The problem is as shown below.

![6](https://github.com/user-attachments/assets/8e2fa08a-35a7-4b24-9c8a-60c72867f4d5)

![9](https://github.com/user-attachments/assets/d1077ceb-e52a-4714-b475-4d773ed5f0b4)

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by Fyj69** [comment]
[KernelSU_Next_bugreport_2024-12-30_10_11.tar.gz](https://github.com/user-attachments/files/18271568/KernelSU_Next_bugreport_2024-12-30_10_11.tar.gz)

**Comment by rifsxd** [comment]
Turn on airplane mode and restart device

**Comment by Fyj69** [comment]
> Turn on airplane mode and restart device

Turn on airplane mode and restart the device, the symptom still exists

**Comment by Fyj69** [comment]
However, choosing the default branch does not have this problem

**Comment by rifsxd** [comment]
> However, choosing the default branch does not have this problem

Wdym default branch? Next?

**Comment by Fyj69** [comment]
> > However, choosing the default branch does not have this problem
> 
> Wdym default branch? Official?

There is no problem using the next branch, but there will be a problem that the module cannot be opened when using next-susfs-4.9.

**Comment by rifsxd** [comment]
> > > However, choosing the default branch does not have this problem
> > 
> > 
> > Wdym default branch? Official?
> 
> There is no problem using the next branch, but there will be a problem that the module cannot be opened when using next-susfs-4.9.

The manager has nothing to do with branches

**Comment by Fyj69** [comment]
> > > > However, choosing the default branch does not have this problem
> > > 
> > > 
> > > Wdym default branch? Official?
> > 
> > 
> > There is no problem using the next branch, but there will be a problem that the module cannot be opened when using next-susfs-4.9.
> 
> The manager has nothing to do with branches

So is this calling module WebUI called at the kernel patch or at the KernelSU patch?

**Comment by rifsxd** [comment]
> > > > > However, choosing the default branch does not have this problem
> > > > 
> > > > 
> > > > Wdym default branch? Official?
> > > 
> > > 
> > > There is no problem using the next branch, but there will be a problem that the module cannot be opened when using next-susfs-4.9.
> > 
> > 
> > The manager has nothing to do with branches
> 
> So is this calling module WebUI called at the kernel patch or at the KernelSU patch?

Module has nothing to do with kernel

**Comment by Fyj69** [comment]
> > > > > > However, choosing the default branch does not have this problem
> > > > > 
> > > > > 
> > > > > Wdym default branch? Official?
> > > > 
> > > > 
> > > > There is no problem using the next branch, but there will be a problem that the module cannot be opened when using next-susfs-4.9.
> > > 
> > > 
> > > The manager has nothing to do with branches
> > 
> > 
> > So is this calling module WebUI called at the kernel patch or at the KernelSU patch?
> 
> Module has nothing to do with kernel

That's strange. Where exactly is the problem?

**Comment by rifsxd** [comment]
> > > > > > > However, choosing the default branch does not have this problem
> > > > > > 
> > > > > > 
> > > > > > Wdym default branch? Official?
> > > > > 
> > > > > 
> > > > > There is no problem using the next branch, but there will be a problem that the module cannot be opened when using next-susfs-4.9.
> > > > 
> > > > 
> > > > The manager has nothing to do with branches
> > > 
> > > 
> > > So is this calling module WebUI called at the kernel patch or at the KernelSU patch?
> > 
> > 
> > Module has nothing to do with kernel
> 
> That's strange. Where exactly is the problem?

How webroot works is the app sets its own domain which is mui.kenrelsu-next.org which then creates its own web servers and when module's weroot is triggered it goes to they domain to display it's index.html maybe either the domain is not being set to your local DNS cache or the webroot is faulty

**Comment by Fyj69** [comment]
> > > > > > > > However, choosing the default branch does not have this problem
> > > > > > > 
> > > > > > > 
> > > > > > > Wdym default branch? Official?
> > > > > > 
> > > > > > 
> > > > > > There is no problem using the next branch, but there will be a problem that the module cannot be opened when using next-susfs-4.9.
> > > > > 
> > > > > 
> > > > > The manager has nothing to do with branches
> > > > 
> > > > 
> > > > So is this calling module WebUI called at the kernel patch or at the KernelSU patch?
> > > 
> > > 
> > > Module has nothing to do with kernel
> > 
> > 
> > That's strange. Where exactly is the problem?
> 
> How webroot works is the app sets its own domain which is mui.kenrelsu-next.org which then creates its own web servers and when module's weroot is triggered it goes to they domain to display it's index.html maybe either the domain is not being set to your local DNS cache or the webroot is faulty

Strangely,building the kernel with the'next'branch allows the module WebUI to open normally,but building the kernel with the'next-susfs-4.9'branch does not allow the module WebUI to open.

**Comment by Fyj69** [comment]
I suspect that there might be some issues with applying the SuSFS patch to the kernel.

**Comment by Fyj69** [comment]
The issue has been resolved. My previous Zygisk version was too old to support the susfs module. Switching to this version solved the problem.

**Comment by rifsxd** [comment]
> The issue has been resolved. My previous Zygisk version was too old to support the susfs module. Upgrading to the latest version fixed it.

well as i said its not KSU-Next related
